### ISSUE TITLE
No feedback on invalid RSS URL

### ISSUE THREAD

**Issue by notramo** [maubot/rss#13]
When specifying an invalid feed url, the bot says it is subscribed. `!rss subscribe https://example.org/nonexistingfeed.xml`

**Comment by tulir** [comment]
Works fine for me, and I'm pretty sure it has always validated the feed when subscribing

**Comment by notramo** [comment]
@tulir What does it do if you send the following message?
```
!rss subscribe https://example.org/nonexistingfeed.xml
```

**Comment by tulir** [comment]
![image](https://user-images.githubusercontent.com/4224639/90267359-17742080-de5e-11ea-8233-22d086ad6e22.png)
