### ISSUE TITLE
Identify Failed Feeds and possibility to delete them

### ISSUE THREAD

**Issue by vsatmydynipnet** [maubot/rss#23]
The log does not show which feed fails, so there is no possibility to delete failed feeds from the DB.

Would be cool to add the possibility to delete e.g. feeds with > 5 continuous fails from the feed db in maubot manager.

**Comment by tulir** [comment]
The log does show which feeds fail, and the database stores the number of consecutive errors so you can easily delete feeds that have failed more than X times.

There seem to be some bugs with resetting the error count when the feed comes back up though
