### ISSUE TITLE
Failed to load feed: generator raised StopIteration

### ISSUE THREAD

**Issue by opk12** [maubot/rss#24]
Hello, I am following the instructions at https://t2bot.io/rssbot/

> `!rss subscribe http://www.openstreetmap.org/api/0.6/notes/feed?bbox=2.224122,48.8547763,2.3311615,48.902157`

returns

> `Failed to load feed: generator raised StopIteration`

**Comment by opk12** [comment]
The cause is [feedparser issue 130](https://github.com/kurtmckee/feedparser/issues/130) which is [fixed on master](https://github.com/kurtmckee/feedparser/pull/131) but not backported to some platforms [including Debian](https://github.com/kurtmckee/feedparser/issues/198).

**Comment by tulir** [comment]
Oops, made a typo in that commit, it's not related to this issue. Anyway, sounds like this wasn't a problem in the bot either
