### ISSUE TITLE
Failed to load feed: <unknown>:23:70: not well-formed (invalid token)

### ISSUE THREAD

**Issue by AnisTaluqdar** [maubot/rss#30]
!rss subscribe https://www.kaggle.com/anistaluqdar/code
!rss subscribe https://github.com/AnisTaluqdar/111_CORA_111

This gives me the error ( Failed to load feed: <unknown>:23:70: not well-formed (invalid token) ), What's wrong?

**Comment by tulir** [comment]
Neither of those look like RSS feeds
